### ISSUE TITLE
SDK isn't compiling on VS 2019

### ISSUE THREAD

**Issue by burque505** [G1ANT-Robot/G1ANT.Sdk#2]
Version: G1ANT.Sdk as of June 16, 2019
Visual Studio version: 16.1.2 (VS 2019)
Issue: I'm trying to compile the SDK with VS 2019, but it is throwing errors related to "Microsoft.VisualStudio.CoreUtility" and "Microsoft.VisualStudio.Threading", both of which were built on higher .NET versions than the SDK requires. 
Thanks in advance for any workarounds, and thank you so much for the free Developer Edition.

**Comment by WiktoriaPrusik** [comment]
Hi @burque505 ,
thank you for your question. The problem you are receiving is due to the missing G1ANT.Language.dll in G1ANT.Sdk library that is downloaded form the NuGet. We are working on it and soon it will compile.

Kind regards,
Wiktoria
G1ANT Team

**Comment by ChrisPrusik** [comment]
Problem Resolved. These VSIX is working fine with all versions Visual Studio Community, Pro and Enterprise starting from 15.0.
https://github.com/G1ANT-Robot/G1ANT.Sdk/raw/master/G1ANT.Sdk.vsix
